package com.twist4english

val tongueTwisters = listOf(
    "Peter Piper picked a peck of pickled peppers"
    ,"A bit of better butter will make my batter better"
    ,"How much wood would a woodchuck chuck if a woodchuck could chuck wood?"
    ,"She sells seashells by the seashore"
    ,"How can a clam cram in a clean cream can?"
    ,"I scream, you scream, we all scream for ice cream"
    ,"Susie works in a shoeshine shop. Where she shines she sits, and where she sits she shines"
    ,"Fuzzy Wuzzy was a bear. Fuzzy Wuzzy had no hair. Fuzzy Wuzzy wasn’t fuzzy, was he?"
    ,"Can you can a can as a canner can can a can?"
    ,"I have got a date at a quarter to eight; I’ll see you at the gate, so don’t be late"
    ,"You know New York, you need New York, you know you need unique New York"
    ,"I saw a kitten eating chicken in the kitchen"
    ,"If a dog chews shoes, whose shoes does he choose?"
    ,"I thought I thought of thinking of thanking you"
    ,"I wish to wash my Irish wristwatch"
    ,"Near an ear, a nearer ear, a nearly eerie ear"
    ,"Eddie edited it"
    ,"Willie’s really weary"
    ,"A big black bear sat on a big black rug"
    ,"Tom threw Tim three thumbtacks"
    ,"He threw three free throws"
    ,"Nine nice night nurses nursing nicely"
    ,"So, this is the sushi chef"
    ,"Four fine fresh fish for you"
    ,"Wayne went to wales to watch walruses"
    ,"Six sticky skeletons"
    ,"Which witch is which?"
    ,"Snap crackle pop"
    ,"Flash message"
    ,"Red Buick, blue Buick"
    ,"Red lorry, yellow lorry"
    ,"Thin sticks, thick bricks"
    ,"Stupid superstition"
    ,"Eleven benevolent elephants"
    ,"Two tried and true tridents"
    ,"Rolling red wagons"
    ,"Black back bat"
    ,"She sees cheese"
    ,"Truly rural"
    ,"Good blood, bad blood"
    ,"Pre-shrunk silk shirts"
    ,"Ed had edited it."
    ,"We surely shall see the sun shine soon"
    ,"Which wristwatches are Swiss wristwatches?"
    ,"Fred fed Ted bread, and Ted fed Fred bread"
    ,"I slit the sheet, the sheet I slit, and on the slitted sheet I sit"
    ,"A skunk sat on a stump and thunk the stump stunk, but the stump thunk the skunk stunk"
    ,"Lesser leather never weathered wetter weather better"
    ,"Biting babies ride battle toys while bumbling boys brave bald biting babies."
)